#!/usr/bin/env python

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    src = bld.path.ant_glob( 'src/*.cpp' )

    bld.stlib(
        features='cxx',
        source=src,
        target='linkedlist',
        includes=['include'],
        export_includes=['linkedlist'])

    bld.program(
        target='linkedlist',
        source=src,
        includes=[ 'include' ],
        export_includes=['include'])
        

    bld.recurse('test')

