#!/usr/bin/env python

def options(opt):
    pass

def configure(conf):
 	pass

def build(bld):
	src = bld.path.ant_glob( 'src/*.cpp' )
	bld.program(
            target='linkedlist',
            source=src,
            includes=[ 'include' ],
            )
