#!/usr/bin/env python

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    bld(
        includes = 'include', 
        export_includes='include', 
        name='stack',
        use='vector')
    bld.recurse('test')

