#!/usr/bin/env python

def options(opt):
    pass

def configure(conf):
    pass
    # conf.env.vector = ['include']

def build(bld):
    bld(
        includes = 'include', 
        export_includes='include', 
        name='vector')

    bld.recurse('test')

